# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('content', models.CharField(max_length=5000)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('views', models.IntegerField()),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
