# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160110_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('content', models.CharField(max_length=5000)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
