# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160118_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
