# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
